remote_theme: pages-themes/modernist@v0.2.0
title: SNAILS - Schema Naming Assessments for Improved LLM-based SQL inference
description: SNAILS is a set of NL-to-SQL-related artifacts designed to explore the effects of schema naming on LLM-based NL-to-SQL performance. It includes a set of real-world databases and associated natural language (NL) to SQL gold query pairs, human-labeled data containing naturalness classifications the tables and columns in the database collection, a model and method for ML-based naturalness classification, and prompting strategies for improving schema identifier naturalness.

plugins:
- jekyll-remote-theme
